### ISSUE TITLE
non_final_argument pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#146] opened 2020-04-01 21:16 UTC
Here it is:

```java
class Foo {
  void bar(int x) { // here
  }
}
```

All method arguments must have `final` modifiers. Once we find an argument without `final`, it's a pattern.

**Comment by 0crat** [comment] 2020-04-01 21:16
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment] 2020-04-21 18:23
@0crat in

**Comment by 0crat** [comment] 2020-04-30 14:49
The job [#146](https://github.com/yegor256/aibolit/issues/146) assigned to @tribals[/z](https://www.0crat.com/u/tribals), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/189abc69-67df-4b2e-86a8-8afc3a6e2ec6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2020-05-05 15:45
@tribals[/z](https://www.0crat.com/u/tribals) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2020-05-10 14:56
The user @tribals[/z](https://www.0crat.com/u/tribals) resigned from [#146](https://github.com/yegor256/aibolit/issues/146), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2020-05-13 08:46
The job [#146](https://github.com/yegor256/aibolit/issues/146) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/a7313ae6-4883-452b-a888-5fcb96e9b560); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2020-05-18 09:52
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment] 2020-05-25 15:14
@yegor256 the puzzle [#349](https://github.com/yegor256/aibolit/issues/349) is still not solved.

**Comment by paulodamaso** [comment] 2020-05-25 17:42
@acheshkov Merged, please close

**Comment by paulodamaso** [comment] 2020-05-28 03:11
@acheshkov ping

**Comment by paulodamaso** [comment] 2020-05-28 03:12
@0crat status

**Comment by 0crat** [comment] 2020-05-28 03:12
> @0crat status ([here](https://github.com/yegor256/aibolit/issues/146#issuecomment-635069619))

@paulodamaso This is what I know about this job in CT5UB7XAP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#146](https://github.com/yegor256/aibolit/issues/146) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) for [15days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @tribals[/z](https://www.0crat.com/u/tribals): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT5UB7XAP?q=%7Bjob%3A%27gh%3Ayegor256%2Faibolit%23146%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment] 2020-05-30 20:20
@acheshkov please close

**Comment by paulodamaso** [comment] 2020-06-06 19:11
@yegor256 @acheshkov Already merged, please close

**Comment by 0crat** [comment] 2020-06-09 11:19
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) the issue is closed not by @yegor256[/z](https://www.0crat.com/u/yegor256) (its creator); I won't close the order; please, re-open it and ask @yegor256[/z](https://www.0crat.com/u/yegor256) to close it

**Comment by paulodamaso** [comment] 2020-06-12 16:13
@yegor256 could you please reopen and close this one? It is rotting in my agenda, and it is already done

**Comment by paulodamaso** [comment] 2020-06-16 17:37
@yegor256 ping

**Comment by 0crat** [comment] 2020-06-22 15:29
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Closed** 2020-06-22 15:29 UTC
Labels: role/DEV, scope

**Comment by 0pdd** [comment] 2020-07-06 14:37
@yegor256 the puzzle [#485](https://github.com/cqfn/aibolit/issues/485) is still not solved.

**Comment by 0crat** [comment] 2020-07-06 14:38
I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment] 2020-07-06 14:38
I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment] 2025-05-28 09:22
@yegor256 3 puzzles [#485](https://github.com/cqfn/aibolit/issues/485), [#751](https://github.com/cqfn/aibolit/issues/751), [#752](https://github.com/cqfn/aibolit/issues/752) are still not solved; solved: [#744](https://github.com/cqfn/aibolit/issues/744).

**Comment by 0pdd** [comment] 2025-05-29 05:58
@yegor256 the puzzle [#752](https://github.com/cqfn/aibolit/issues/752) is still not solved; solved: [#485](https://github.com/cqfn/aibolit/issues/485), [#744](https://github.com/cqfn/aibolit/issues/744), [#751](https://github.com/cqfn/aibolit/issues/751).

**Comment by 0pdd** [comment] 2025-06-26 05:04
@yegor256 all 4 puzzles are solved here: [#485](https://github.com/cqfn/aibolit/issues/485), [#744](https://github.com/cqfn/aibolit/issues/744), [#751](https://github.com/cqfn/aibolit/issues/751), [#752](https://github.com/cqfn/aibolit/issues/752).
