### ISSUE TITLE
CLI. aibolit recommendations pipeline(s)

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#153] opened 2020-04-02 09:09 UTC
Aibolit CLI has to recommend which patterns mostly affect the quality of the code. We call it `recommendation pipeline`. The `recommendation pipeline` consists of:

1. Take in Java Class File or Project Folder
2. Calculate all metrics and patterns for this file
3. Run ML model to get ranked lists of patterns
4. Prepare recommendations for a user based on the ranked patterns

For today, some prototype of such pipeline implemented but it has the following issues: 

1. There is no support of Project Folder at step 1 ```aibolit  recommend --folder path_to_folder```
2. Some metrics to calculate requires to run PMD tool (java tool)
3. Pretty print of recommendations to console and file

**Comment by acheshkov** [comment] 2020-04-02 09:17
@0crat in

**Comment by 0crat** [comment] 2020-04-14 16:07
The job [#153](https://github.com/yegor256/aibolit/issues/153) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/0849c36b-dacc-4454-a77a-a337bcb84b1d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment] 2020-04-16 14:01
@acheshkov Which of these issues should I address first?

**Comment by 0crat** [comment] 2020-04-19 16:54
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by acheshkov** [comment] 2020-04-19 18:33
@paulodamaso I'm going to assign this issue to @lyriccoder, if you don't mind

**Comment by paulodamaso** [comment] 2020-04-20 11:06
@acheshkov No problem for me

**Comment by paulodamaso** [comment] 2020-04-21 19:29
@0crat wait for reassignment

**Comment by paulodamaso** [comment] 2020-04-25 17:38
@acheshkov PLease reassign it

**Comment by 0crat** [comment] 2020-04-27 16:09
The job [#153](https://github.com/yegor256/aibolit/issues/153) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/fc43e20e-4478-4f3c-93ad-bda4d88f641a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Closed** 2020-05-21 08:23 UTC
Labels: role/DEV, scope

**Comment by 0crat** [comment] 2020-05-21 08:45
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) the issue is closed not by @acheshkov[/z](https://www.0crat.com/u/acheshkov) (its creator); I won't close the order; please, re-open it and ask @acheshkov[/z](https://www.0crat.com/u/acheshkov) to close it
