### ISSUE TITLE
Recommend failed.

### ISSUE THREAD

**Issue by IlyaMoskva** [yegor256/aibolit#287] opened 2020-05-13 09:37 UTC
Failed with recommend.
Aibolit Version 1.0.0a1

[MavenSlice.zip](https://github.com/yegor256/aibolit/files/4621048/MavenSlice.zip)

**Comment by 0crat** [comment] 2020-05-13 09:37
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment] 2020-05-13 16:25
@0crat out

**Comment by 0crat** [comment] 2020-05-13 16:27
The job [#287](https://github.com/yegor256/aibolit/issues/287) assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/45ec9a9a-4b9b-4814-8c47-6c3cc6ba85de); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2020-05-13 16:27
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/287#issuecomment-628101123))

@acheshkov GitHub issue is still open, won't close

**Comment by 0crat** [comment] 2020-05-13 16:27
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/287#issuecomment-628101123))

@acheshkov Job [#287](https://github.com/yegor256/aibolit/issues/287) is not in the agenda of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), can't set title

**Closed** 2020-05-14 10:42 UTC
Labels: role/DEV, scope

**Comment by 0crat** [comment] 2020-05-14 10:59
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) the issue is closed not by @IlyaMoskva (its creator); I won't close the order; please, re-open it and ask @IlyaMoskva to close it

**Comment by 0crat** [comment] 2020-05-18 16:51
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.
