### ISSUE TITLE
Analyse 20 `top` java OSS projects and 20 `random` with Aibolit

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#458] opened 2020-06-28 16:35 UTC
Measure Aibolit Score for each project in the table. 

I want to see the table: 

| project | stars | aibolit score |
|--------|------|--------------|
| | | |

Then I want to measure the Average aibolit score amount two groups `top` and `random`.

**Comment by 0crat** [comment] 2020-06-28 17:09
The job [#458](https://github.com/yegor256/aibolit/issues/458) assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/9905e47b-1cc9-404c-afd3-063e48312625); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by lyriccoder** [comment] 2020-07-02 07:09
is it done? Can we merge PR?

**Closed** 2020-07-03 15:03 UTC
Labels: role/DEV, scope

**Comment by 0crat** [comment] 2020-07-03 15:20
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) the issue is closed not by @acheshkov[/z](https://www.0crat.com/u/acheshkov) (its creator); I won't close the order; please, re-open it and ask @acheshkov[/z](https://www.0crat.com/u/acheshkov) to close it
