### ISSUE TITLE
Why we check here only the value of the first snippet?

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#430] opened 2020-06-20 10:41 UTC
https://github.com/yegor256/aibolit/blob/6c139802a3e914c825cc14039a8309095faa712b/aibolit/model/model.py#L218

**Comment by 0crat** [comment] 2020-06-20 10:45
The job [#430](https://github.com/yegor256/aibolit/issues/430) assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/7aeb2910-5645-4402-9fc1-c29e64defe1b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2020-06-20 10:45
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by lyriccoder** [comment] 2020-06-25 06:47
fixed in https://github.com/yegor256/aibolit/pull/444

**Closed by lyriccoder** 2020-06-25 06:47 UTC
Labels: role/DEV, scope

**Comment by 0crat** [comment] 2020-06-25 07:04
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) the issue is closed not by @acheshkov[/z](https://www.0crat.com/u/acheshkov) (its creator); I won't close the order; please, re-open it and ask @acheshkov[/z](https://www.0crat.com/u/acheshkov) to close it
