### ISSUE TITLE
Why not making classes having value() method implement interface???

### ISSUE THREAD

**Issue by fanifieiev** [yegor256/aibolit#123] opened 2020-03-27 00:19 UTC
Reviewing some pull requests I came across a lot of classes having `value()` method.
So, why not making them implement some interface?
I am doing a python project [PyEO](https://github.com/fanifieiev/pyeo) , where I try to follow EO paradigm and try to use the same approach as in [Cactoos](https://github.com/yegor256/cactoos).
Here is an example of Scalar interface (https://github.com/fanifieiev/pyeo/blob/master/pyeo/scalar/base.py), which is implemented by other classes.
I am not an expert in Python, I am from Java world, so I might be mistaken, but it is worth looking at.

**Comment by 0crat** [comment] 2020-03-27 00:19
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment] 2020-03-27 09:05
@fanifieiev Hi! Yes, good point. The project requires its principal architecture. We bear that in mind.

**Comment by acheshkov** [comment] 2020-04-07 08:41
@0crat in

**Comment by 0crat** [comment] 2020-04-20 13:29
The job [#123](https://github.com/yegor256/aibolit/issues/123) assigned to @tribals[/z](https://www.0crat.com/u/tribals), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/4cf020c9-b6a6-459c-bf5c-e18eccc491b5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2020-04-25 13:42
@tribals[/z](https://www.0crat.com/u/tribals) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2020-04-30 13:23
The user @tribals[/z](https://www.0crat.com/u/tribals) resigned from [#123](https://github.com/yegor256/aibolit/issues/123), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2020-05-01 05:46
The job [#123](https://github.com/yegor256/aibolit/issues/123) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/388a44ba-239a-44e1-b762-5948c0442367); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2020-05-06 06:44
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment] 2020-05-09 03:49
@0crat wait for #275 review

**Comment by lyriccoder** [comment] 2020-05-12 08:18
The problem is that each pattern is a Singleton and `value()` is a _static method_. _static method_ cannot be overridden. 

That's why we do not need abstract class here

**Comment by paulodamaso** [comment] 2020-05-13 16:17
@lyriccoder  What should I do here then?

**Comment by lyriccoder** [comment] 2020-05-13 19:12
I will talk to @acheshkov and will decide what to do. 
@acheshkov Will we merge PR?

**Comment by paulodamaso** [comment] 2020-05-18 20:12
@acheshkov Do we have any resolution on this one?

**Comment by paulodamaso** [comment] 2020-05-25 17:04
@lyriccoder @acheshkov I think that we shouldn't use singletons because singleton is a bad pattern. This stated, we could make the method non-static and override it as needed

**Comment by paulodamaso** [comment] 2020-05-30 20:00
@acheshkov Ping please take a look at this

**Comment by paulodamaso** [comment] 2020-06-16 17:36
@acheshkov ping

**Closed** 2020-06-22 15:30 UTC
Labels: role/DEV, scope, waiting
