### ISSUE TITLE
nested_loop pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#137] opened 2020-04-01 20:52 UTC
Here it is:

```java
class Foo {
  void foo() {
    white (true) {
      for (;;) { // here
      }  
    }
  }
}
```

Once we find a loop (`for` or `while`) inside another loop (`for` or `while`) it's a pattern.

**Comment by 0crat** [comment] 2020-04-01 20:53
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment] 2020-04-02 08:47
For those who will implement: take a look at already implemented patterns `nested_blocks`, it may save your time and code.

**Comment by 0crat** [comment] 2020-04-09 12:55
The job [#137](https://github.com/yegor256/aibolit/issues/137) assigned to @acheshkov[/z](https://www.0crat.com/u/acheshkov), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/21ed0a5c-0567-4420-924f-c73a07d8cb9c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @acheshkov[/z](https://www.0crat.com/u/acheshkov) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Closed** 2020-04-09 16:53 UTC
Labels: role/DEV, scope

**Comment by acheshkov** [comment] 2020-04-09 17:07
@yegor256, please close

**Comment by 0crat** [comment] 2020-04-09 17:10
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @yegor256[/z](https://www.0crat.com/u/yegor256) (its creator); I won't close the order; please, re-open it and ask @yegor256[/z](https://www.0crat.com/u/yegor256) to close it

**Comment by 0crat** [comment] 2020-04-14 14:08
@acheshkov[/z](https://www.0crat.com/u/acheshkov) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2020-04-15 01:29
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@cb1f8598a82e, thread: PQ-CT5UB7XAP
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [reason, priority, job, cause, _parent_sig, flow, voluntarily, login]
```

[0.53.1](https://github.com/zerocracy/farm): CID: [c018fe1c-7cd3-407f-a06f-77ecadef7a65](https://www.0crat.com/footprint/CT5UB7XAP/c018fe1c-7cd3-407f-a06f-77ecadef7a65), Type: "Order was canceled"

**Comment by 0crat** [comment] 2020-04-15 01:33
@acheshkov[/z](https://www.0crat.com/u/acheshkov) resigned from [#137](https://github.com/yegor256/aibolit/issues/137), since the job is not in scope anymore
