### ISSUE TITLE
null_check pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#89] opened 2020-03-18 15:15 UTC
This is the pattern:

```
class Foo {
  private String z;
  void x() {
    if (this.z == null) { // here!
      throw new RuntimeException("oops");
    }
  }
}
```

The check for `null` is the pattern.

The pattern should not check constructors.

**Comment by yegor256** [comment] 2020-03-18 15:15
@acheshkov FYI

**Comment by tribals** [comment] 2020-03-18 16:22
@yegor256 Can you please assign it to me?

**Comment by 0crat** [comment] 2020-03-20 16:49
The job [#89](https://github.com/yegor256/aibolit/issues/89) assigned to @tribals[/z](https://www.0crat.com/u/tribals), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/df75b119-40a1-45fa-8904-006c59b78224); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by tribals** [comment] 2020-03-20 20:51
@yegor256 @acheshkov Need more clarification which cases should be considered a pattern.

- Should it catch `null`s when it is left operand rather right?
- Should it catch "not equal" operations?
- Should it catch checks involving method calls - `Optional.ofNulable()`, `Objects.requireNotNull()`, possible others?

**Comment by tribals** [comment] 2020-03-23 11:48
@yegor256 @acheshkov Bump7

**Comment by tribals** [comment] 2020-03-24 14:57
@0crat status

**Comment by 0crat** [comment] 2020-03-24 15:04
> @0crat status ([here](https://github.com/yegor256/aibolit/issues/89#issuecomment-603288099))

@tribals This is what I know about this job in [CT5UB7XAP](https://www.0crat.com/p/CT5UB7XAP), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#89](https://github.com/yegor256/aibolit/issues/89) is [in scope](http://www.zerocracy.com/policy.html#14) for 4days
  * The role is `DEV`
  * The job is assigned to @tribals[/z](https://www.0crat.com/u/tribals) for [4days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @tribals[/z](https://www.0crat.com/u/tribals) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT5UB7XAP?q=%7Bjob%3A%27gh%3Ayegor256%2Faibolit%2389%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment] 2020-03-24 15:11
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @yegor256[/z](https://www.0crat.com/u/yegor256) (its creator); I won't close the order; please, re-open it and ask @yegor256[/z](https://www.0crat.com/u/yegor256) to close it

**Comment by tribals** [comment] 2020-03-24 15:43
@yegor256 Can you please re-open issue and close it again by yourself? I don't have enough permissions to re-open.

**Comment by tribals** [comment] 2020-03-25 13:31
@yegor256 Bump. I need to close ticket.

**Comment by 0crat** [comment] 2020-03-25 14:06
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @acheshkov[/z](https://www.0crat.com/u/acheshkov) is the architect now

**Comment by tribals** [comment] 2020-03-25 15:42
@acheshkov Please, reopen issue and close it by yourself, so I will count as done by me in Zerocrat.

**Comment by acheshkov** [comment] 2020-03-26 08:44
Thx

**Comment by 0crat** [comment] 2020-03-26 08:44
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Closed** 2020-03-26 08:44 UTC
