### ISSUE TITLE
Docker. Base version of the Docker recommendation image.

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#262] opened 2020-05-06 10:02 UTC

**Comment by 0crat** [comment] 2020-05-06 10:03
The job [#262](https://github.com/yegor256/aibolit/issues/262) assigned to @acheshkov[/z](https://www.0crat.com/u/acheshkov), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/c51b36b7-30ae-4d7d-ae8f-e0eaa1c1e0ee); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @acheshkov[/z](https://www.0crat.com/u/acheshkov) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Closed** 2020-05-06 15:41 UTC
Labels: role/DEV, scope

**Comment by 0crat** [comment] 2020-05-06 16:00
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @acheshkov[/z](https://www.0crat.com/u/acheshkov) (its creator); I won't close the order; please, re-open it and ask @acheshkov[/z](https://www.0crat.com/u/acheshkov) to close it

**Comment by 0crat** [comment] 2020-05-11 10:46
@acheshkov[/z](https://www.0crat.com/u/acheshkov) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.
