### ISSUE TITLE
Model sensitivity threshold bug

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#310] opened 2020-05-15 07:01 UTC
Recommend the same pattern what th=1.0

**Comment by 0crat** [comment] 2020-05-15 07:02
The job [#310](https://github.com/yegor256/aibolit/issues/310) assigned to @acheshkov[/z](https://www.0crat.com/u/acheshkov), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/a3b28d3c-601c-4393-b6c2-221e090e995d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @acheshkov[/z](https://www.0crat.com/u/acheshkov) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Closed** 2020-05-15 09:20 UTC
Labels: role/DEV, scope

**Comment by 0crat** [comment] 2020-05-15 09:53
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @acheshkov[/z](https://www.0crat.com/u/acheshkov) (its creator); I won't close the order; please, re-open it and ask @acheshkov[/z](https://www.0crat.com/u/acheshkov) to close it
