### ISSUE TITLE
Appveyor Windows build failed

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#295] opened 2020-05-14 07:21 UTC

**Comment by acheshkov** [comment] 2020-05-14 07:22
@0crat out

**Comment by acheshkov** [comment] 2020-05-14 07:22
`set PATH=C:\Python37;C:\Python37\Scripts;%PATH%`

**Comment by 0crat** [comment] 2020-05-14 07:22
The job [#295](https://github.com/yegor256/aibolit/issues/295) assigned to @acheshkov[/z](https://www.0crat.com/u/acheshkov), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/7e620259-5d0a-43f6-b19b-3f6261c6071a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @acheshkov[/z](https://www.0crat.com/u/acheshkov) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment] 2020-05-14 07:23
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/295#issuecomment-628442235))

@acheshkov GitHub issue is still open, won't close

**Closed** 2020-05-14 09:57 UTC
Labels: role/DEV, scope

**Comment by 0crat** [comment] 2020-05-14 10:14
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @acheshkov[/z](https://www.0crat.com/u/acheshkov) (its creator); I won't close the order; please, re-open it and ask @acheshkov[/z](https://www.0crat.com/u/acheshkov) to close it

**Comment by 0crat** [comment] 2020-05-19 07:46
@acheshkov[/z](https://www.0crat.com/u/acheshkov) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.
