### ISSUE TITLE
non_final_class pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#143] opened 2020-04-01 21:11 UTC
Once we see a class that doesn't have `final` modifier, it's a pattern. It's a good practice to make all classes final: https://www.yegor256.com/2014/11/20/seven-virtues-of-good-object.html

**Comment by 0crat** [comment] 2020-04-01 21:11
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment] 2020-04-09 12:52
The job [#143](https://github.com/yegor256/aibolit/issues/143) assigned to @acheshkov[/z](https://www.0crat.com/u/acheshkov), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/bbc905db-cbcd-4ceb-a87e-812f59be9586); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @acheshkov[/z](https://www.0crat.com/u/acheshkov) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Closed** 2020-04-10 13:51 UTC
Labels: role/DEV, scope

**Comment by acheshkov** [comment] 2020-04-10 14:04
@yegor256 it's done, please close

**Comment by 0crat** [comment] 2020-04-10 14:08
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @yegor256[/z](https://www.0crat.com/u/yegor256) (its creator); I won't close the order; please, re-open it and ask @yegor256[/z](https://www.0crat.com/u/yegor256) to close it

**Comment by 0crat** [comment] 2020-04-14 12:45
@acheshkov[/z](https://www.0crat.com/u/acheshkov) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.
