### ISSUE TITLE
Aibolit CLI should return ExitCode=1

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#333] opened 2020-05-21 06:42 UTC
Aibolit CLI should return ExitCode=1 If any issues are found

**Comment by acheshkov** [comment] 2020-05-21 06:47
@0crat out

**Comment by 0crat** [comment] 2020-05-21 06:55
The job [#333](https://github.com/yegor256/aibolit/issues/333) assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/96ec8488-7109-41b5-af26-5c93be30c0c5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2020-05-21 06:56
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/333#issuecomment-631916121))

@acheshkov Job [#333](https://github.com/yegor256/aibolit/issues/333) is not in the agenda of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), can't set title

**Comment by 0crat** [comment] 2020-05-21 06:56
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/333#issuecomment-631916121))

@acheshkov GitHub issue is still open, won't close

**Closed** 2020-05-21 12:43 UTC
Labels: role/DEV, scope

**Comment by 0crat** [comment] 2020-05-21 13:01
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) the issue is closed not by @acheshkov[/z](https://www.0crat.com/u/acheshkov) (its creator); I won't close the order; please, re-open it and ask @acheshkov[/z](https://www.0crat.com/u/acheshkov) to close it
