### ISSUE TITLE
summary line is not informative enough

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#429] opened 2020-06-19 19:00 UTC
Currently I see this:

```
Total average score: 2.2559776388960775
```

How about this instead:

```
Total score: 2.25, files seen: 159, patterns found: 585, LoC: 7584
```

(no need to show the entire score down to every digit, just two digits after the dot is enough)

**Comment by 0crat** [comment] 2020-06-19 19:00
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment] 2020-06-20 16:09
The job [#429](https://github.com/yegor256/aibolit/issues/429) assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/a7c54bf5-64a3-4d0d-878a-71cc45b5ac06); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by lyriccoder** [comment] 2020-06-22 09:04
is it ok to show NCSS instead of LOC? LOC is not so informative. You can have a full class with imports and spaces.
What do u think @yegor256?

**Comment by lyriccoder** [comment] 2020-06-25 14:48
`format=xml` will contain such the tags:

```
	<header>
		<score>18.86666666666667</score>
		<!--datetime in ms-->
		<datetime>1593095179271</datetime>
		<version>0.0.0</version>
		<!--Files with errors-->
		<files>3</files>
		<patterns>15</patterns>
		<ncss>632</ncss>
		<cmd>D:/git/aibolit/aibolit/__main__.py recommend --full --folder D:\target\0001\fast --format=xml</cmd>
		<exit_code>1</exit_code>
	</header>
```

`format=compact` will contain the following lines:

`Total score: 18.87, files seen: 3, patterns found: 15, ncss: 632`

format=long won't contain the info about patterns number since there are grouped by lines code, not by patterns:
`
Total score: 18.87, files seen: 3, ncss 632`

**Closed** 2020-06-26 10:26 UTC
Labels: role/DEV, scope

**Comment by 0crat** [comment] 2020-06-26 10:47
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @yegor256[/z](https://www.0crat.com/u/yegor256) (its creator); I won't close the order; please, re-open it and ask @yegor256[/z](https://www.0crat.com/u/yegor256) to close it
