### ISSUE TITLE
many_primary_ctors pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#99] opened 2020-03-18 19:01 UTC
Here:

```java
class Book {
  private final int a;
  Book(int x) {
    this.x = a;
  }
  Book() {
    this.x = 0;
  }
}
```

Here, we have two constructors and each of them have atribute-assigning statements. Each constructor is primary. Read here for more info: https://www.yegor256.com/2015/05/28/one-primary-constructor.html

**Comment by yegor256** [comment] 2020-03-25 13:55
@0crat in

**Comment by acheshkov** [comment] 2020-03-25 14:56
@0crat assign @tribals

**Comment by 0crat** [comment] 2020-03-25 15:07
> @0crat assign @tribals  ([here](https://github.com/yegor256/aibolit/issues/99#issuecomment-603887671))

@acheshkov The job [#99](https://github.com/yegor256/aibolit/issues/99) assigned to @tribals[/z](https://www.0crat.com/u/tribals), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/a8db7124-22dd-4334-a741-4a2f8e696e07); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by tribals** [comment] 2020-03-25 17:23
@yegor256 Is it correct that a primary constructor is one that assigns values to instance variables?

**Comment by 0crat** [comment] 2020-03-30 16:07
@tribals[/z](https://www.0crat.com/u/tribals) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2020-03-31 13:16
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @yegor256[/z](https://www.0crat.com/u/yegor256) (its creator); I won't close the order; please, re-open it and ask @yegor256[/z](https://www.0crat.com/u/yegor256) to close it

**Comment by 0crat** [comment] 2020-03-31 16:32
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Closed** 2020-03-31 16:32 UTC
